In [2]:
from data_process import *
#from models import *
#from utility import *
#from train_evaluate import *
import pandas as pd
import os
from tqdm import tqdm

ModuleNotFoundError: No module named 'torch'

In [2]:
#CHANGE THE SKIP TOKEN

#st = sequence
#lst = 
#a = next token
#user_id = user
#skip = skip
#buy = was the next a hit
#display(pd.read_csv('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/transition_store_test.csv'))

,st,lst,a,buy,user_id,skip
0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,151,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,"[0, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,150,1,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
2,"[0, 151, 150, 0, 0, 0, 0, 0, 0, 0, 0]",2,149,1,0,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]"
3,"[0, 151, 150, 149, 0, 0, 0, 0, 0, 0, 0]",3,148,1,0,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]"
4,"[0, 151, 150, 149, 148, 0, 0, 0, 0, 0, 0]",4,147,1,0,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...
19314,"[5, 21195, 21194, 0, 0, 0, 0, 0, 0, 0, 0]",2,21193,1,5,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]"
19315,"[5, 21195, 21194, 21193, 0, 0, 0, 0, 0, 0, 0]",3,21192,1,5,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]"
19316,"[5, 21195, 21194, 21193, 21192, 0, 0, 0, 0, 0, 0]",4,21191,1,5,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]"
19317,"[5, 21195, 21194, 21193, 21192, 21191, 0, 0, 0...",5,21190,1,5,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]"
19318,"[5, 21195, 21194, 21193, 21192, 21191, 21190, ...",6,21189,1,5,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]"

In [ ]:
m = DataModule('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/', 32)

In [2]:
filepath = '/mnt/data2/pavans/pavans/training_set'
test_file = os.listdir(filepath)[1]

df = pd.read_csv(os.path.join(filepath, test_file))
df

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,long_pause_before_play,hist_user_behavior_n_seekfwd,hist_user_behavior_n_seekback,hist_user_behavior_is_shuffle,hour_of_day,date,premium,context_type,hist_user_behavior_reason_start,hist_user_behavior_reason_end
0,10_0000172c-a619-44a1-9284-6f88ba876507,1,20,t_10a02b6d-bd97-40e0-907a-b964f0e8c3e7,False,True,True,False,0,0,...,0,0,0,False,20,2018-07-24,False,user_collection,trackdone,fwdbtn
1,10_0000172c-a619-44a1-9284-6f88ba876507,2,20,t_79c5d73d-9949-4a25-a98e-9839a616d400,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
2,10_0000172c-a619-44a1-9284-6f88ba876507,3,20,t_612e16f4-14e2-4e4c-9b97-14ab82240a47,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
3,10_0000172c-a619-44a1-9284-6f88ba876507,4,20,t_cd661951-833f-4392-b101-f83568a0ae70,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
4,10_0000172c-a619-44a1-9284-6f88ba876507,5,20,t_8f9f2397-334b-48ee-9120-96d9ddf32f92,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,backbtn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257778,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,16,20,t_363c666e-73aa-4b97-8c65-667cd0e190a0,False,False,False,True,0,1,...,0,0,1,False,11,2018-07-25,True,catalog,fwdbtn,trackdone
3257779,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,17,20,t_e6dbaa5a-419a-4b45-a1c1-09867a88f4ec,False,False,False,True,0,1,...,0,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257780,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,18,20,t_eacd7e86-70a8-4207-a412-238cc55c1112,False,False,False,True,0,1,...,0,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257781,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,19,20,t_2a55e695-7894-42aa-b920-52d1cbaf164c,False,False,False,True,0,0,...,1,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257782,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,20,20,t_a66ea088-b357-449a-8a1e-64dd0b8d6cb5,False,False,True,False,0,0,...,1,0,0,False,11,2018-07-25,True,catalog,trackdone,endplay

In [ ]:
sessions = list()
skips = list()
vocab = set()
session_ids = list()
cols = ['session_position', 'track_id_clean', 'skip_level'] #+ ['skip_1', 'skip_2', 'skip_3']
#skip_level = lambda df_: [4 - x for x in range(1, 4) if df_[f'skip_{x}'].bool() else 0] #0 - 3 in order of most severe skip
for s, df_s in tqdm(df.groupby(['session_id'])):
    df_s.sort_values(by = ['session_position'], axis=0, inplace=True)
    df_s['skip_level'] = ((df_s['skip_1'].astype(int) + df_s['skip_2'].astype(int) + df_s['skip_3'].astype(int)))
    df_s = df_s[cols]
    sessions.append(df_s['track_id_clean'].to_list())
    skips.append(df_s['skip_level'])
    vocab = vocab.union(set(sessions[-1]))
    session_ids.append(s)
print(len(session_ids) == len(sessions))

 20%|â–ˆâ–ˆ        | 39779/195829 [02:51<18:27, 140.86it/s]

In [21]:
print( 3 % 4)

3